
git:
  submodules: true

notifications:
  email:
    - sj.kim@alcherainc.com

language: cpp
compiler: clang

os: osx

addons:
  homebrew:
    packages:
      - ninja
      - tree

matrix:
  include:
    - osx_image: xcode10.3
      env:
        - SHARED=true

    - osx_image: xcode11.2
      env:
        - SHARED=true

    - osx_image: xcode11.2
      script:
        - cmake ..
          -DCMAKE_TOOLCHAIN_FILE=../ios-cmake/ios.toolchain.cmake
        - cmake --build .

install:
  - cmake --version

before_script:
  - mkdir build
  - cd build

script:
  - cmake .. -G Ninja -DBUILD_SHARED_LIBS=${SHARED}
  - cmake --build .

after_success:
  - tree -L 2 ${TRAVIS_BUILD_DIR}
  # - file ./libsocket.a
  # - otool -L ./libsocket.a
