
language: cpp
compiler: clang

os: osx

addons:
  homebrew:
    packages:
      - ninja
      - tree

matrix:
  include:
    - osx_image: xcode10.3
      env:
        - SHARED=true

    - osx_image: xcode11.2
      env:
        - SHARED=true

install:
  - cmake --version

before_script:
  - mkdir build
  - cd build

script:
  - cmake .. -G Ninja -DBUILD_SHARED_LIBS=${SHARED}
  - cmake --build .

after_success:
  - tree ${TRAVIS_BUILD_DIR}
  # - file ./libsocket.a
  # - otool -L ./libsocket.a
