
git:
  submodules: true

notifications:
  email:
    - sj.kim@alcherainc.com

language: cpp
compiler: clang

os: osx

addons:
  homebrew:
    packages:
      - ninja
      - tree

matrix:
  include:
    - osx_image: xcode10.3
      env:
        - SHARED=true
        - TARGET=x86_64

    - osx_image: xcode11.2
      env:
        - SHARED=true
        - TARGET=x86_64

    - osx_image: xcode11.2
      env:
        - TARGET=iPhoneOS
      script:
        - cmake ..
          -DCMAKE_TOOLCHAIN_FILE=../ios-cmake/ios.toolchain.cmake
          -DENABLE_VISIBILITY=true
        - cmake --build .
        - cmake --build . --target install

install:
  - cmake --version
  - if [ ${TRAVIS_OS_NAME} == "osx" ]; then
    brew info llvm;
    fi

before_script:
  - mkdir build
  - cd build

script:
  - cmake .. -G Ninja -DBUILD_SHARED_LIBS=${SHARED} -DTARGET=${TARGET}
  - cmake --build .
  - cmake --build . --target install

after_success:
  - tree -L 2 ${TRAVIS_BUILD_DIR}
  # - file ./libsocket.a
  # - otool -L ./libsocket.a

before_deploy:
  - cd ${TRAVIS_BUILD_DIR}
  - export ZIP_NAME="socket_${TRAVIS_OSX_IMAGE}_${TARGET}.zip"
  - zip -r ${ZIP_NAME} install

deploy:
  - provider: releases
    api_key: "${MAINTAINER_GITHUB_TOKEN}"
    file: ${ZIP_NAME}
    skip_cleanup: true
    prerelease: true
    on:
      tags: true
